[WIP] Note viewing key permissioning system
AztecProtocol/aztec-v1 pull request #315
Opened 2019-09-05 11:51 UTC by thomas-waite

## Summary
This PR implements a note viewing key permissioning system. 

It allows third parties to be granted access to a note, by the note owner adding an IES encrypted viewing key to the `metaData` of the note. 

A `noteAccess` mapping has been implemented to keep track of which Ethereum addresses have been granted view access to a note. Being granted approval gives that address permission to call `updateNoteMetaData()` - this allows the approved party to in turn grant view access to additional parties. 

The `noteAccess` mapping is based on the block timestamp. Specifically, it is a mapping of a `noteHash` to a mapping of `addressID` to `blockTimeStamp`:

```
    mapping(bytes32 => mapping(bytes32 => uint256)) public noteAccess;
``` 

`addressID` is `keccak256(approvedAddress, noteHash)`. 

In order to extract addresses from the `metaData` of a note, a `MetaDataUtils.sol` library has been written.

## Todo's
The permissioning step in `ZkAssetBase.updateNoteMetaData()` needs explicitly testing. It's function is currently implied from querying the `noteAccess` mapping in certain scenarios - using a `ZkAssetTest` for which the permission requirement was removed. 

This was done due to the difficulty in creating a note - you need to know the public key - owned by a truffle account. Only truffle accounts can send transactions.

## Testing instructions
Various test cases to check the permissioning flow have been added to `ZkAsset.js`.

2019-09-06 11:02 UTC, ArnSch requested changes

2019-09-06 11:02 UTC, ArnSch commented on packages/protocol/contracts/ERC1724/base/ZkAssetBase.sol
> +        bytes32 addressID = keccak256(abi.encodePacked(msg.sender, noteHash));
This strikes me as superfluous if you're doing a two dimensional mapping.

Either do a mapping from `keccak256(abi.encodePacked(msg.sender, noteHash)) => uint256` or a two dimensional mapping from `noteHash => address => uint256`. Both will result in a unique timestamp per note per address.

2019-09-06 11:02 UTC, ArnSch commented on packages/protocol/contracts/interfaces/IZkAsset.sol
> +    event ApprovedAddress(address indexed addressApproved, bytes32 indexed noteHash, address contractAddress);
Should contractAddress be indexed to make finding all approved notes for a user for an asset easier?

2019-09-06 11:02 UTC, ArnSch commented on packages/protocol/contracts/libs/MetaDataUtils.sol
> +        * 0xe1 - L_addresses : approvedAddresses
Where is L_addresses set? I assume that it's the first word at 0xe1, but would be good to document.

2019-09-06 11:02 UTC, ArnSch commented on packages/protocol/contracts/libs/MetaDataUtils.sol
> +        * (0xe1 + L_addresses + L_encryptedViewKeys) - (0xe1 + L_addresses + L_encryptedViewKeys + L_appData) : appData
ditto for L_encryptedViewKeys

2019-09-06 11:02 UTC, ArnSch commented on packages/protocol/contracts/libs/MetaDataUtils.sol
> +                        add(0xe1, 0x20)  // go to the start of addresses, jump over first word
I think it's worth the overhead to sense check that you're not going out of the bounds of `0xe1 + L_addresses`. Could be as simple as checking that addressPos < L_addresses.

2019-09-06 11:02 UTC, ArnSch commented on packages/protocol/test/ERC1724/ZkAsset.js
>               * Using ZkAssetTest as the ZkAsset here. ZkAssetTest has the safety feature
I don't feel comfortable with this solution. You can get the accounts used in ganache from a set mnemonic (see @charlie-g-cowan's branch).

This isn't really testing the zkAsset implementation of updateNoteMetadata. As it stands, we could drastically change that method implementation in zkAssetBase and this test would still pass.

2019-09-06 11:02 UTC, ArnSch commented on packages/protocol/test/ERC1724/ZkAsset.js
>              const zkAssetTest = await ZkAssetTest.new(ace.address, erc20.address, scalingFactor);
Ditto on zkAssetTest

2019-09-06 11:02 UTC, ArnSch commented on packages/protocol/contracts/test/ERC1724/ZkAssetTest.sol
> +        bytes32 confidentialTotalBurned, , , , bool canAdjustSupply) = ace.getRegistry(address(this));
```suggestion
        (
            ,,
            bytes32 confidentialTotalMinted,
            bytes32 confidentialTotalBurned
            ,,,,
            bool canAdjustSupply
        ) = ace.getRegistry(address(this));
```

2019-09-06 14:03 UTC, thomas-waite commented on packages/protocol/contracts/interfaces/IZkAsset.sol
> +    event ApprovedAddress(address indexed addressApproved, bytes32 indexed noteHash, address contractAddress);
Chatted with the extension team about this to decide which fields should be indexed and arrived at the above. Will double check with them and mention your point, makes sense

2019-09-06 14:05 UTC, thomas-waite commented on packages/protocol/contracts/interfaces/IZkAsset.sol
> +    event ApprovedAddress(address indexed addressApproved, bytes32 indexed noteHash, address contractAddress);
Just spoke to Joe. They didn't need `contractAddress` indexing and now also don't need this event - so removing this address

2019-09-06 14:08 UTC, thomas-waite commented on packages/protocol/contracts/libs/MetaDataUtils.sol
> +        * 0xe1 - L_addresses : approvedAddresses
`L_addresses` is supplied and set by the client in the extension.

The extension has a variety of `metaData` encoding functions, which take a user's `metaData` intended for a note, and encodes it according to this ABI outlined in `MetaDataUtils.sol` . Will add a comment explaining this

2019-09-06 14:10 UTC, thomas-waite commented on packages/protocol/contracts/libs/MetaDataUtils.sol
> +        * 0xe1 - L_addresses : approvedAddresses
The first word at `0xe1` is the number of addresses. `L_addresses` isn't so much as set, rather it's just the length in memory that the addresses take up

2019-09-06 14:12 UTC, thomas-waite commented on packages/protocol/contracts/libs/MetaDataUtils.sol
> +        * (0xe1 + L_addresses + L_encryptedViewKeys) - (0xe1 + L_addresses + L_encryptedViewKeys + L_appData) : appData
Same as above

2019-09-06 14:15 UTC, thomas-waite commented on packages/protocol/contracts/ERC1724/base/ZkAssetBase.sol
> +        bytes32 addressID = keccak256(abi.encodePacked(msg.sender, noteHash));
Good point, my bad. It should just be a mapping of `keccak256(abi.encodePacked(msg.sender, noteHash)) => uint256`

2019-09-06 14:25 UTC, thomas-waite commented on packages/protocol/test/ERC1724/ZkAsset.js
>               * Using ZkAssetTest as the ZkAsset here. ZkAssetTest has the safety feature
Fully agree, the current testing setup is not good enough. This is one of the todo's I mentioned for the WIP PR - was implementing after this review

2019-09-06 14:25 UTC, thomas-waite commented on packages/protocol/test/ERC1724/ZkAsset.js
>              const zkAssetTest = await ZkAssetTest.new(ace.address, erc20.address, scalingFactor);
Same as above

2019-09-06 14:50 UTC, ArnSch commented on packages/protocol/contracts/libs/MetaDataUtils.sol
> +        * 0xe1 - L_addresses : approvedAddresses
Yes, I more mean documenting that the first word at 0xe1 is in fact num of addresses, same for L_encryptedViewKeys

2019-09-08 05:21 UTC, thomas-waite commented on packages/protocol/contracts/libs/MetaDataUtils.sol
> +        * 0xe1 - L_addresses : approvedAddresses
Gotcha, will do

2019-09-08 05:25 UTC, thomas-waite commented on packages/protocol/contracts/test/ERC1724/ZkAssetTest.sol
> +        bytes32 confidentialTotalBurned, , , , bool canAdjustSupply) = ace.getRegistry(address(this));
Done

2019-09-08 05:41 UTC, thomas-waite commented on packages/protocol/contracts/libs/MetaDataUtils.sol
> +                        add(0xe1, 0x20)  // go to the start of addresses, jump over first word
Sure, good idea - done

2019-09-09 09:03 UTC, ArnSch approved these changes
LGTM

2019-09-09 09:06 UTC, merged