Feat/hot fixes
AztecProtocol/aztec-v1 pull request #509
Opened 2020-03-30 13:15 UTC by joeandrews

## Summary

This code is already deployed in SDK V1.11.0

## Description

Small updates to the event service to stop the SDK incorrectly selecting the block number of the last synced note for multiple metamask accounts. 

This PR also enables DAI permit in the SDK.

2020-03-30 13:17 UTC, joeandrews commented
We are planning a wider refactor of this code today as its been the source of lots of balance bugs within the SDK.

2020-03-30 13:31 UTC, ArnSch requested changes
Just a small cleanup request, otherwise 👍

2020-03-30 13:31 UTC, ArnSch commented on packages/extension/package.json
> +    "version": "1.11.0",
I believe this should actually be re-set to `0.0.0-semantically-released`.

2020-03-30 13:31 UTC, ArnSch commented on packages/extension/src/background/services/EventService/index.js
>              const assets = await this.syncedAssets({ networkId });
A clean up of this file before merge would be good.

2020-03-31 09:06 UTC, merged

2020-07-23 10:16 UTC, ArnSch commented
:tada: This PR is included in version 0.18.1 :tada:

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2020-07-23 10:19 UTC, ArnSch commented
:tada: This PR is included in version 1.7.1 :tada:

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2020-07-23 10:24 UTC, ArnSch commented
:tada: This PR is included in version 1.12.0 :tada:

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: